# -*- coding: utf-8 -*-
"""Earthquake.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Wd0G_6hHfDwLndmvfN6Z58Z2Fg2lgcH

# **Combining collab with kaggle**
"""

!pip install -q kaggle
#INSTALL KAGGLE

from google.colab import files
files.upload()

#CREATE A KAGGLE FOLDER
!mkdir -p ~/.kaggle

!cp kaggle.json ~/.kaggle/

#COPY KAGGLE JSONTO FOLDER CREATED

#PERMISSION
!chmod 600 ~/.kaggle/kaggle.json

# TO LIST THE DATASETS IN KAGGLE
!kaggle datasets list

"""# **Importing the Dataset**






"""

!kaggle datasets download -d ahmeduzaki/earthquake-alert-prediction-dataset
# Used the given dataset

!unzip earthquake-alert-prediction-dataset.zip
#unzip it

"""# **STARTING THE DATA PREPROCESSING **"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
#importing libraries

"""# **LOADING THE DATASETS**


"""

import pandas as pd

df = pd.read_csv("earthquake_alert_balanced_dataset.csv")
df.head()

df.info()

df.columns

"""# **Features Distribution Plots**"""

df['magnitude'].hist()
#Distribution of Magnitude

df['depth'].hist()
#Distribution of depth

df['cdi'].hist()
#CDI — Community Determined Intensity
#CDI = how strong people felt the earthquake.

df['mmi'].hist()
#MMI — Modified Mercalli Intensity
#MMI = physical damage level based on observation.

df['sig'].hist()
#SIG — Significance
#Higher SIG = more important / more dangerous event.

df.dtypes

import seaborn as sns
import matplotlib.pyplot as plt

numeric_df = df.select_dtypes(include=['float64', 'int64'])

sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

import seaborn as sns
sns.countplot(x=df['alert'])

"""# **Handling  Missing Values**"""

# Check missing
print("Missing values before filling:\n", df.isnull().sum())

# Duplicate values
df.duplicated().sum()

#to see duplicate values'
df[df.duplicated()]

"""# **Removing Duplicates**"""

#To remove duplicate values
df = df.drop_duplicates()

#For confirmation
df.duplicated().sum()

# Fill alert with mode (most frequent)
df['alert'].fillna(df['alert'].mode()[0], inplace=True)
print("\nMissing values after filling:\n", df.isnull().sum())

"""# **Encoding Categorical Data**"""

# Encode categorical column "alert"
#Convert text → numbers.
le = LabelEncoder()
df['alert_encoded'] = le.fit_transform(df['alert'])

print("\nAlert label encoding:")
print(df[['alert', 'alert_encoded']].head())

"""# **Normalization** / **Scaling** Numeric Values"""

# Feature engineering
df['magnitude_depth_ratio'] = df['magnitude'] / (df['depth'] + 1)
df['intensity_score'] = df['cdi'] + df['mmi']

# Normalize numerical columns/ Data scaling
num_cols = ['magnitude', 'depth', 'cdi', 'mmi', 'sig', 'magnitude_depth_ratio', 'intensity_score']
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

print("\nScaled numerical features (first 5 rows):")
print(df[num_cols].head())

"""# **Feature Engineering**"""

# Feature engineering
# This cell is now empty as its content has been moved to the scaling cell.

#  Save preprocessed dataset
df.to_csv("earthquake_preprocessed.csv", index=False)
df.head()

"""# **Feature Selection**"""

numeric_df = df.select_dtypes(include=['float64', 'int64'])
numeric_df.corr()

"""## **MODEL TRAINING**"""

X = df[['magnitude', 'depth', 'cdi', 'mmi', 'sig', 'intensity_score', 'magnitude_depth_ratio']]
y = df['alert_encoded']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""**Logistic Regression Model**"""

from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(max_iter=200)
log_model.fit(X_train, y_train)

log_pred = log_model.predict(X_test)

"""**DECISION TREE**"""

from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier(max_depth=5)
tree_model.fit(X_train, y_train)

tree_pred = tree_model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

log_acc = accuracy_score(y_test, log_pred)
print("Logistic Regression Accuracy:", log_acc)
print("\nLogistic Report:\n", classification_report(y_test, log_pred))
print("\nLogistic Confusion Matrix:\n", confusion_matrix(y_test, log_pred))

tree_acc = accuracy_score(y_test, tree_pred)
print("\nDecision Tree Accuracy:", tree_acc)
print("\nDecision Tree Report:\n", classification_report(y_test, tree_pred))
print("\nDecision Tree Confusion Matrix:\n", confusion_matrix(y_test, tree_pred))

import numpy as np

importance = tree_model.feature_importances_
for name, score in zip(X.columns, importance):
    print(name, ":", score)

"""# **Advanced model training**"""

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

!pip install xgboost

"""# Random Forest Model"""

rf = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

rf_acc = accuracy_score(y_test, rf_pred)
print("RANDOM FOREST ACCURACY:", rf_acc)
print("\nRF CLASSIFICATION REPORT:\n", classification_report(y_test, rf_pred))
print("\nRF CONFUSION MATRIX:\n", confusion_matrix(y_test, rf_pred))

for name, score in zip(X.columns, rf.feature_importances_):
    print(name, ":", score)

"""# **XGBoost Model**"""

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.1,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='mlogloss'
)

xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)

print("\nXGBOOST ACCURACY:", accuracy_score(y_test, xgb_pred))
print("\nXGBOOST CLASSIFICATION REPORT:\n", classification_report(y_test, xgb_pred))
print("\nXGBOOST CONFUSION MATRIX:\n", confusion_matrix(y_test, xgb_pred))

xgb.get_booster().get_score()

import joblib
joblib.dump(xgb, "best_model_xgboost.pkl")

import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X = df[
    ["magnitude", "depth", "cdi", "mmi", "sig",
     "intensity_score", "magnitude_depth_ratio"]
]

y = df["alert_encoded"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""# **Gradient boosting**"""

gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train, y_train)

gb_pred = gb.predict(X_test)

baseline_acc = accuracy_score(y_test, gb_pred)
print("Baseline GB Accuracy:", baseline_acc)

"""# **Cross validation**"""

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = []

for train_idx, val_idx in cv.split(X_train, y_train):
    X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    model = GradientBoostingClassifier(random_state=42)
    model.fit(X_tr, y_tr)
    preds = model.predict(X_val)

    cv_scores.append(accuracy_score(y_val, preds))

print("CV Scores:", cv_scores)
print("Mean CV Accuracy:", np.mean(cv_scores))

plt.bar(range(1, 6), cv_scores)
plt.axhline(np.mean(cv_scores), linestyle="--", label="Mean")
plt.xlabel("Fold")
plt.ylabel("Accuracy")
plt.title("Gradient Boosting Cross-Validation")
plt.legend()
plt.show()

"""# hyper parameter **tuning**"""

param_grid = {
    "n_estimators": [100, 200],
    "learning_rate": [0.05, 0.1],
    "max_depth": [3, 5],
    "subsample": [0.8, 1.0]
}

gb_grid = GridSearchCV(
    GradientBoostingClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1,
    verbose=2
)

gb_grid.fit(X_train, y_train)

print("Best Parameters:", gb_grid.best_params_)
print("Best CV Accuracy:", gb_grid.best_score_)

best_gb = gb_grid.best_estimator_
best_pred = best_gb.predict(X_test)

print("Final Test Accuracy:", accuracy_score(y_test, best_pred))
print(classification_report(y_test, best_pred))

plt.bar(
    ["Baseline GB", "Tuned GB"],
    [baseline_acc, accuracy_score(y_test, best_pred)]
)
plt.ylim(0, 1)
plt.ylabel("Accuracy")
plt.title("Gradient Boosting – Improvement After Tuning")
plt.show()

"""# **Manual checking**"""

import joblib
model = joblib.load("best_model_xgboost.pkl")

magnitude = float(input("Enter magnitude: "))
depth = float(input("Enter depth: "))
cdi = float(input("Enter CDI: "))
mmi = float(input("Enter MMI: "))
sig = float(input("Enter SIG score: "))

intensity_score = cdi + mmi
magnitude_depth_ratio = magnitude / (depth + 1)

import numpy as np

input_data = np.array([[magnitude, depth, cdi, mmi, sig,
                        intensity_score, magnitude_depth_ratio]])

prediction = model.predict(input_data)[0]
print("Encoded Prediction:", prediction)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df["alert"])  # your original dataset labels

decoded = le.inverse_transform([prediction])[0]
print("Final Alert:", decoded)

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LinearSegmentedColormap

# COLOR STYLES
color_map = {
    "green": ("#00FF00", "#009900"),      # light → dark
    "yellow": ("#FFFF00", "#E6C200"),
    "orange": ("#FFA500", "#CC8400"),
    "red": ("#FF0000", "#990000")
}

if decoded not in color_map:
    print("Invalid alert:", decoded)
else:
    light_color, dark_color = color_map[decoded]

    # background
    gradient = np.linspace(0, 1, 256)
    gradient = np.vstack((gradient, gradient))

    cmap = LinearSegmentedColormap.from_list("alert_cmap", [light_color, dark_color])
    plt.figure(figsize=(6, 4))
    plt.imshow(gradient, aspect='auto', cmap=cmap)

    # Border styling
    for side in ['top', 'bottom', 'left', 'right']:
        plt.gca().spines[side].set_color('black')
        plt.gca().spines[side].set_linewidth(4)
    plt.text(
        0.5, 0.5,
        f"EARTHQUAKE ALERT:\n{decoded.upper()}",
        fontsize=26,
        fontweight='bold',
        color="black",
        ha='center',
        va='center'
    )

    plt.axis("off")
    plt.show()

"""WEEK 5"""

import pandas as pd
import matplotlib.pyplot as plt

importance = best_gb.feature_importances_

fi_df = pd.DataFrame({
    "Feature": X.columns,
    "Importance": importance
}).sort_values(by="Importance", ascending=False)

print(fi_df)

plt.figure(figsize=(8,5))
plt.barh(fi_df["Feature"], fi_df["Importance"])
plt.gca().invert_yaxis()
plt.xlabel("Importance Score")
plt.title("Feature Importance – Gradient Boosting")
plt.show()

"""Error Analysis"""

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(y_test, best_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix – Gradient Boosting")
plt.show()

"""Classification Report"""

from sklearn.metrics import classification_report

print(classification_report(y_test, best_pred))

"""Misclassified Samples"""

misclassified = X_test[y_test != best_pred]
misclassified["Actual"] = y_test[y_test != best_pred]
misclassified["Predicted"] = best_pred[y_test != best_pred]

misclassified.head(10)

"""shap

"""

!pip install shap

import shap

# Initialize the explainer with the model's predict_proba method and the training data as masker
explainer = shap.Explainer(best_gb.predict_proba, X_train)
shap_values = explainer(X_test)

# Plot SHAP values for the first output class (index 0)
shap.plots.bar(shap_values[..., 0])

import joblib

joblib.dump(best_gb, "best_gradient_boosting_model.pkl")

print(best_gb)